//===========================================================================//
//
// Purpose: Achievements
//
//===========================================================================//

#ifndef ACHIEVEMENTS_TF_H
#define ACHIEVEMENTS_TF_H
#ifdef _WIN32
#pragma once
#endif

#include "achievementmgr.h"
#include "baseachievement.h"

enum
{
	ACHIEVEMENT_TF_GET_TURRETKILLS = 1,
	ACHIEVEMENT_TF_KILL_NEMESIS,
	ACHIEVEMENT_TF_GET_CONSECUTIVEKILLS_NODEATHS,
	ACHIEVEMENT_TF_GET_HEALED_BYENEMY,
	ACHIEVEMENT_TF_PLAY_GAME_FRIENDSONLY,
	ACHIEVEMENT_TF_WIN_MULTIPLEGAMES,
	ACHIEVEMENT_TF_GET_MULTIPLEKILLS,
	ACHIEVEMENT_TF_WIN_2FORT_NOENEMYCAPS,
	ACHIEVEMENT_TF_WIN_WELL_MINIMUMTIME,
	ACHIEVEMENT_TF_WIN_HYDRO_NOENEMYCAPS,
	ACHIEVEMENT_TF_WIN_DUSTBOWL_NOENEMYCAPS,
	ACHIEVEMENT_TF_WIN_GRAVELPIT_NOENEMYCAPS,
	ACHIEVEMENT_TF_PLAY_GAME_EVERYCLASS,
	ACHIEVEMENT_TF_PLAY_GAME_EVERYMAP,
	ACHIEVEMENT_TF_GET_HEALPOINTS,
	ACHIEVEMENT_TF_BURN_PLAYERSINMINIMIMTIME,
	ACHIEVEMENT_TF_GET_HEADSHOTS,
	ACHIEVEMENT_TF_GENERAL_KILL_ENEMIES_AFTER_TELEPORTING,

	ACHIEVEMENT_TF_PYRO_KILL_TAUNT,
	ACHIEVEMENT_TF_HEAVY_KILL_TAUNT,
	ACHIEVEMENT_TF_SCOUT_TAUNT_KILL,
	ACHIEVEMENT_TF_SPY_TAUNT_KILL,
	ACHIEVEMENT_TF_SNIPER_TAUNT_KILL,
	ACHIEVEMENT_TF_SOLDIER_KILL_TAUNT,
	ACHIEVEMENT_TF_DEMOMAN_TAUNT_KILL,
	ACHIEVEMENT_TF_ENGINEER_TAUNT_KILL,

	ACHIEVEMENT_LFE_BEAT_HL2,
	ACHIEVEMENT_LFE_BEAT_HL2EP1,
	ACHIEVEMENT_LFE_BEAT_HL2EP2,
	ACHIEVEMENT_LFE_BEAT_HLS,
	ACHIEVEMENT_LFE_BEAT_P1,
	ACHIEVEMENT_LFE_KILL_COMBINE,
	ACHIEVEMENT_LFE_KILL_ZOMBIE,
	ACHIEVEMENT_LFE_KILL_ANTLION,
	ACHIEVEMENT_LFE_KILL_CANCOP,
	ACHIEVEMENT_LFE_DEV_ABUSE,
	ACHIEVEMENT_LFE_KILL_GARGANTUA_WITH_FLAME,
	ACHIEVEMENT_LFE_KILL_SNIPER_WITH_SNIPER,
	ACHIEVEMENT_LFE_TAUNT_BREEN,
	ACHIEVEMENT_LFE_TAUNT_AR3,
	ACHIEVEMENT_LFE_SAVE_SANDY_LASZO,
	ACHIEVEMENT_LFE_DESTORY_CITADEL,
	ACHIEVEMENT_LFE_ESCAPE_CITY17,
	ACHIEVEMENT_LFE_LAUNCH_ROCKET,
	ACHIEVEMENT_LFE_MANOFFEWWORDS,
};

#endif // ACHIEVEMENTS_TF_H
